apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: sample-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data"
